"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['randomizer.py']
DATA_FILES = []
OPTIONS = {
}
OPTIONS.update(iconfile="images/random_icon.icns",  plist=dict(CFBundleIdentifier='edu.fullerton.ecs.mshafae'))

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
